export const CONNECT_SOCKET_BEGIN = 'CONNECT/SOCKET/BEGIN';
export const CONNECT_SOCKET_RESOLVE = 'CONNECT/SOCKET/RESOLVE';
// export const CONNECT_SOCKET_REJECT = 'CONNECT/SOCKET/REJECT;

export const POST_TWEET_BEGIN = 'POST/TWEET/BEGIN';
export const POST_TWEET_RESOLVE = 'POST/TWEET/RESOLVE';
export const POST_TWEET_REJECT = 'POST/TWEET/REJECT';

export const GET_GEOLOCATION_BEGIN = 'SOCKET/GET/GEOLOCATION/BEGIN';
export const GET_GEOLOCATION_RESOLVE = 'SOCKET/GET/GEOLOCATION/RESOLVE';
// export const GET_GEOLOCATION_REJECT = 'SOCKET/GET/GEOLOCATION/REJECT';
